Repository LordNani/netcracker-eshop, pull requests merged in 2021-06, with the labels that each got.

#24 Created sonarcloud workflow
  .github/release-drafter.yml
  .github/workflows/codecov.yml
  .github/workflows/label-verify.yml
  .github/workflows/release.yml
  .github/workflows/sonarcloud.yml
  backend/pom.xml
Labels: type:config-backend, type:features-backend

#27 Update label-verify.yml
  .github/workflows/label-verify.yml
Labels: type:fix-backend

#33 Feature/product crud
  backend/pom.xml
  backend/src/main/java/com/eshop/backend/BackendApplication.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/AuthorizedUser/AuthorizedUserDao.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/AuthorizedUser/CustomerRowMapper.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/MainDao.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/Product/ProductDao.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/Product/ProductDaoImpl.java
  backend/src/main/java/com/eshop/backend/DAO/Models/AuthorizedUser.java
  backend/src/main/java/com/eshop/backend/DAO/Models/Product.java
  backend/src/main/java/com/eshop/backend/DAO/Models/Role.java
  backend/src/main/java/com/eshop/backend/auth/controllers/LoginController.java
  backend/src/main/java/com/eshop/backend/auth/controllers/RegistrationController.java
  backend/src/main/java/com/eshop/backend/auth/dto/LoginRequstDTO.java
  backend/src/main/java/com/eshop/backend/auth/jwt/ConfigBCrypt.java
  backend/src/main/java/com/eshop/backend/auth/jwt/JWTAuthenticationFilter.java
  backend/src/main/java/com/eshop/backend/auth/jwt/JWTAuthorizationFilter.java
  backend/src/main/java/com/eshop/backend/auth/jwt/SecurityConstants.java
  backend/src/main/java/com/eshop/backend/auth/jwt/UserDetailsServiceImpl.java
  backend/src/main/java/com/eshop/backend/auth/mail/EmailSenderService.java
  backend/src/main/java/com/eshop/backend/auth/security/SpringFoxConfig.java
  backend/src/main/java/com/eshop/backend/auth/security/WebSecurity.java
  backend/src/main/java/com/eshop/backend/product/catalog/controllers/ProductCRUDController.java
  backend/src/main/java/com/eshop/backend/product/catalog/controllers/ProductSortFilterController.java
  backend/src/main/java/com/eshop/backend/product/catalog/dto/ProductSortDTO.java
  backend/src/main/java/com/eshop/backend/product/catalog/mapper/ProductMapper.java
  backend/src/main/java/com/eshop/backend/product/catalog/service/ProductService.java
  backend/src/main/java/com/eshop/backend/product/catalog/service/ProductServiceImp.java
  backend/src/main/resources/application.properties
Labels: type:config-backend, type:features-backend

#35 fix develop errors
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/AuthorizedUser/AuthorizedUserDaoImpl.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/EmailToken/EmailTokenDao.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/EmailToken/EmailTokenDaoImpl.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/controllers/AdminControllerImp.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/controllers/CourierControllerImp.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/controllers/ManagerControllerImp.java
  backend/src/main/java/com/eshop/backend/DAO/Models/EmailToken.java
  backend/src/main/java/com/eshop/backend/product/catalog/service/MainService.java
  backend/src/main/java/com/eshop/backend/product/catalog/service/ProductServiceImp.java
  backend/src/main/resources/db/migration/init/V2__create_tables.sql
Labels: type:fix-backend

#37 KIEV21DEVS-26 Fixing
  .github/release-drafter.yml
  .github/workflows/codecov.yml
  .github/workflows/dockerhub.yml
  .github/workflows/label-verify.yml
  .github/workflows/release.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ticket-verify.yml
  backend/.dockerignore
  backend/Dockerfile
  backend/pom.xml
  backend/src/main/java/com/eshop/backend/product/catalog/mapper/ProductMapper.java
  backend/src/main/java/com/eshop/backend/product/catalog/service/ProductServiceImp.java
  backend/src/main/resources/TEST
Labels: type:config

#39 KIEV21DEVS-26 Update job titles
  .github/workflows/codecov.yml
  .github/workflows/label-verify.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ticket-verify.yml
Labels: type:fix

#41 KIEV21DEVS-128 Feature/aut user gets
  backend/pom.xml
  backend/src/main/java/com/eshop/backend/DAO/Controller/AuthorizeduserController.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/Admin/AdminDAO.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/Admin/AdminDAOImp.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/AuthorizedUser/AuthorizedUserDao.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/AuthorizedUser/AuthorizedUserDaoImpl.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/Courier/CourierDAO.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/Courier/CourierDAOImp.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/Manager/ManagerController.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/Manager/ManagerControllerImp.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/Services/AuthorizeduserService.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/Services/AuthorizeduserServiceImp.java
  backend/src/main/java/com/eshop/backend/DAO/Models/AuthorizedUser.java
  backend/src/main/java/com/eshop/backend/DAO/Models/AuthorizedUserTableData.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/db/migration/init/V1__create_tables.sql
  backend/src/main/resources/db/migration/init/V2__create_tables.sql
  backend/src/main/resources/db/migration/init/V3_CREATE_TABLES.SQL
  frontend/src/app/_model/user.ts
  frontend/src/app/_service/rest.service.ts
  frontend/src/app/authorization/login/login.component.html
  frontend/src/app/authorization/registration/registration.component.html
Labels: type:features

#46 KIEV21DEVS-26 Fixed multiple labels
  .github/workflows/label-verify.yml
Labels: type:features, type:fix

#52 Feature/search2
  backend/src/main/java/com/eshop/backend/admin/AdminController.java
  backend/src/main/java/com/eshop/backend/auth/LoginController.java
  backend/src/main/java/com/eshop/backend/auth/config/WebSecurity.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDaoImpl.java
  backend/src/main/java/com/eshop/backend/auth/dto/LoginRequstDTO.java
  backend/src/main/java/com/eshop/backend/dao/DataAccess/AuthorizedUser/AuthorizedUserDao.java
  backend/src/main/java/com/eshop/backend/dao/DataAccess/Services/AuthorizeduserService.java
  backend/src/main/java/com/eshop/backend/dao/DataAccess/Services/AuthorizeduserServiceImp.java
  backend/src/main/resources/db/migration/init/V2__create_tables.sql
  frontend/src/app/_model/managers.ts
  frontend/src/app/_service/rest.service.ts
  frontend/src/app/account/profile/profile.component.html
  frontend/src/app/account/search/search.component.html
  frontend/src/app/account/search/search.component.ts
  frontend/src/app/app-routing.module.ts
Labels: type:config

#53 KIEV21DEVS-26 fixing the plothole
  .github/release-drafter.yml
  .github/workflows/codecov.yml
  .github/workflows/dockerhub.yml
  .github/workflows/release.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ticket-verify.yml
Labels: type:config, type:fix

#54 KIEV21DEVS-1231 Fixed most of the errors
  backend/src/main/java/com/eshop/backend/admin/AdminController.java
  backend/src/main/java/com/eshop/backend/admin/services/AdminService.java
  backend/src/main/java/com/eshop/backend/admin/services/AdminServiceImp.java
  backend/src/main/java/com/eshop/backend/auth/LoginController.java
  backend/src/main/java/com/eshop/backend/auth/RegistrationController.java
  backend/src/main/java/com/eshop/backend/auth/config/Role.java
  backend/src/main/java/com/eshop/backend/auth/dao/email/EmailTokenDaoImpl.java
  backend/src/main/java/com/eshop/backend/auth/dao/models/EmailTokenModel.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDao.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDaoImpl.java
  backend/src/main/java/com/eshop/backend/auth/dto/LoginRequstDTO.java
  backend/src/main/java/com/eshop/backend/auth/exceptions/ControllerAdvisor.java
  backend/src/main/java/com/eshop/backend/auth/exceptions/dto/ErrorMessageDTO.java
  backend/src/main/java/com/eshop/backend/auth/mail/EmailSenderService.java
  backend/src/main/java/com/eshop/backend/auth/utils/Role.java
  backend/src/main/java/com/eshop/backend/catalog/ProductCRUDController.java
  backend/src/main/java/com/eshop/backend/catalog/dto/ProductSortDTO.java
  backend/src/main/java/com/eshop/backend/catalog/service/ProductService.java
  backend/src/main/java/com/eshop/backend/catalog/service/ProductServiceImp.java
  backend/src/main/java/com/eshop/backend/dao/DataAccess/AuthorizedUser/AuthorizedUserDao.java
  backend/src/main/java/com/eshop/backend/dao/DataAccess/Services/AuthorizeduserService.java
  backend/src/main/java/com/eshop/backend/dao/DataAccess/Services/AuthorizeduserServiceImp.java
  backend/src/main/java/com/eshop/backend/product/dao/ProductDao.java
  backend/src/main/java/com/eshop/backend/product/dao/models/ProductModel.java
  backend/src/main/java/com/eshop/backend/user/dao/models/AuthorizedUserModel.java
  backend/src/main/java/com/eshop/backend/utils/DbInitializer.java
  backend/src/main/resources/db/migration/init/V2__create_tables.sql
Labels: type:config, type:fix

#55 KIEV21DEVS-134 small frontend fixes
  backend/src/main/java/com/eshop/backend/auth/config/WebSecurity.java
  frontend/src/app/_service/product/product.service.ts
  frontend/src/app/account/profile/profile.component.html
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/products/product-list/product-list.component.html
  frontend/src/app/products/product-search/product-search.component.html
  frontend/src/app/products/product-search/product-search.component.ts
  frontend/src/app/products/products.module.ts
Labels: type:fix

#56 KIEV21DEVS-1421 Fixing dockerhub missing component
  backend/.dockerignore
  backend/Dockerfile
Labels: type:config, type:fix

#57 KIEV21DEVS-141 fix problem after last merge
  backend/src/main/java/com/eshop/backend/auth/LoginController.java
  backend/src/main/java/com/eshop/backend/auth/config/WebSecurity.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDaoImpl.java
  backend/src/main/java/com/eshop/backend/auth/exceptions/ControllerAdvisor.java
  backend/src/main/java/com/eshop/backend/auth/exceptions/WrongEmailOrPasswordException.java
  backend/src/main/java/com/eshop/backend/catalog/service/ProductServiceImp.java
  backend/src/main/java/com/eshop/backend/product/dao/ProductDaoImpl.java
  frontend/src/app/_helper/auth.guard.ts
  frontend/src/app/_helper/error.interceptor.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
Labels: type:fix

#58 KIEV21DEVS-128 Search 3 merge fix
  backend/src/main/java/com/eshop/backend/admin/AdminController.java
  backend/src/main/java/com/eshop/backend/admin/services/AdminServiceImp.java
  backend/src/main/java/com/eshop/backend/auth/config/WebSecurity.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDao.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDaoImpl.java
  backend/src/main/resources/db/migration/init/V2__create_tables.sql
  frontend/src/app/_service/rest.service.ts
  frontend/src/app/account/search/search.component.html
  frontend/src/app/account/search/search.component.ts
  frontend/src/app/app.module.ts
Labels: type:fix

#60 KIEV21DEVS-134 products pagination and filtration
  backend/src/main/java/com/eshop/backend/catalog/ProductCRUDController.java
  backend/src/main/java/com/eshop/backend/catalog/service/ProductService.java
  backend/src/main/java/com/eshop/backend/catalog/service/ProductServiceImp.java
  backend/src/main/java/com/eshop/backend/product/dao/ProductDao.java
  backend/src/main/java/com/eshop/backend/product/dao/ProductDaoImpl.java
  backend/src/main/java/com/eshop/backend/product/dao/models/FilterModel.java
  frontend/src/app/_model/filters.ts
  frontend/src/app/_service/product/product.service.ts
  frontend/src/app/products/categories-part/categories-part.component.ts
  frontend/src/app/products/product-list/product-list.component.html
  frontend/src/app/products/product-list/product-list.component.ts
  frontend/src/app/products/product-search/product-search.component.html
  frontend/src/app/products/product-search/product-search.component.ts
  frontend/src/app/products/products.module.ts
Labels: type:features, type:fix

#66 KIEV21DEVS-343 CSS + new product features
  backend/src/main/java/com/eshop/backend/catalog/ProductCRUDController.java
  backend/src/main/java/com/eshop/backend/catalog/service/ProductService.java
  backend/src/main/java/com/eshop/backend/catalog/service/ProductServiceImp.java
  backend/src/main/java/com/eshop/backend/product/dao/ProductDao.java
  backend/src/main/java/com/eshop/backend/product/dao/ProductDaoImpl.java
  frontend/src/app/_service/product/product.service.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.css
  frontend/src/app/app.component.html
  frontend/src/app/main-page/main-page.component.html
  frontend/src/app/main-page/main-page.component.ts
  frontend/src/app/products/categories-part/categories-part.component.css
  frontend/src/app/products/categories-part/categories-part.component.html
  frontend/src/app/products/product-card/product-card.component.css
  frontend/src/app/products/product-card/product-card.component.html
  frontend/src/app/products/product-card/product-card.component.ts
  frontend/src/app/products/product-create/product-create.component.html
  frontend/src/app/products/product-edit/product-edit.component.html
  frontend/src/app/products/product-list/product-list.component.css
  frontend/src/app/products/product-list/product-list.component.html
  frontend/src/app/products/product-list/product-list.component.ts
  frontend/src/app/products/product-manager/product-manager.component.html
  frontend/src/app/products/product-search/product-search.component.html
  frontend/src/app/products/product/product.component.css
  frontend/src/app/products/product/product.component.html
  frontend/src/app/products/product/product.component.ts
  frontend/src/app/products/products.module.ts
  frontend/src/app/work-space/manager-workspace/manager-workspace.component.css
  frontend/src/app/work-space/manager-workspace/manager-workspace.component.html
Labels: type:features, type:fix
