Repository LordNani/netcracker-eshop, pull requests merged in 2021-07, with the labels that each got.

#67 KIEV21DEVS-131 fix order by products
  frontend/src/app/products/product-list/product-list.component.html
  frontend/src/app/products/product-list/product-list.component.ts
  frontend/src/app/shopping-cart/shopping-cart.component.html
Labels: type:fix

#70 KIEV21DEVS-127\ KIEV21DEVS-239\ KIEV21DEVS-245
  backend/pom.xml
  backend/src/main/java/com/eshop/backend/Socket/Greeting.java
  backend/src/main/java/com/eshop/backend/Socket/Message.java
  backend/src/main/java/com/eshop/backend/Socket/NotificationDispatcher.java
  backend/src/main/java/com/eshop/backend/Socket/NotificationsController.java
  backend/src/main/java/com/eshop/backend/Socket/WebSocketConfig.java
  backend/src/main/java/com/eshop/backend/admin/AdminController.java
  backend/src/main/java/com/eshop/backend/auth/config/WebSecurity.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDaoImpl.java
  backend/src/main/java/com/eshop/backend/courier/CourierController.java
  backend/src/main/java/com/eshop/backend/courier/CustomerRowMapperForCourier.java
  backend/src/main/java/com/eshop/backend/courier/dto/courierDto.java
  backend/src/main/java/com/eshop/backend/courier/model/CourierModel.java
  backend/src/main/java/com/eshop/backend/courier/service/CourierService.java
  backend/src/main/java/com/eshop/backend/courier/service/CourierServiceImp.java
  backend/src/main/resources/db/migration/init/V1__create_tables.sql
  backend/src/main/resources/db/migration/init/V2__create_tables.sql
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/_model/coucab.ts
  frontend/src/app/_model/courierDto.ts
  frontend/src/app/_service/rest.service.ts
  frontend/src/app/account/courier-cabinet/coucab.component.css
  frontend/src/app/account/courier-cabinet/coucab.component.html
  frontend/src/app/account/courier-cabinet/coucab.component.ts
  frontend/src/app/account/courier-cabinet/courier-cabinet.spec.component.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/socket/notifications/notification.component.css
  frontend/src/app/socket/notifications/notification.component.html
  frontend/src/app/socket/notifications/notification.component.spec.ts
  frontend/src/app/socket/notifications/notification.component.ts
Labels: type:features

#73 Feature/account
  backend/lib/javax.ejb.jar
  backend/lib/javax.jms.jar
  backend/lib/javax.persistence.jar
  backend/lib/javax.resource.jar
  backend/lib/javax.servlet.jsp.jar
  backend/lib/javax.servlet.jsp.jstl.jar
  backend/lib/javax.transaction.jar
  backend/pom.xml
  backend/src/main/java/com/eshop/backend/BackendApplication.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/AuthorizedUser/AuthorizedUserDaoImpl.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/AuthorizedUser/CustomerRowMapper.java
  backend/src/main/java/com/eshop/backend/DAO/DataAccess/Employee/EmployeeMapper.java
  backend/src/main/java/com/eshop/backend/DAO/Models/AuthorizedUser.java
  backend/src/main/java/com/eshop/backend/DAO/Models/Employee.java
  backend/src/main/java/com/eshop/backend/admin/AdminController.java
  backend/src/main/java/com/eshop/backend/auth/config/WebSecurity.java
  backend/src/main/java/com/eshop/backend/auth/controllers/LoginController.java
  backend/src/main/java/com/eshop/backend/search/SearchController.java
  backend/src/main/java/com/eshop/backend/search/SearchRequestDTO.java
  backend/src/main/java/com/eshop/backend/user/dao/models/AuthorizedUserModel.java
  backend/src/main/java/com/eshop/backend/utils/Employee/EmployeeDao.java
  backend/src/main/java/com/eshop/backend/utils/Employee/EmployeeService.java
  backend/src/main/resources/application.properties
  frontend/src/app/_model/managers.ts
  frontend/src/app/_model/user.ts
  frontend/src/app/_service/rest.service.ts
  frontend/src/app/account/profile/profile.component.css
  frontend/src/app/account/profile/profile.component.html
  frontend/src/app/account/profile/profile.component.ts
  frontend/src/app/account/search/search.component.css
  frontend/src/app/account/search/search.component.html
  frontend/src/app/account/search/search.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/nav-bar/pages/nav-bar/nav-bar.component.html
  frontend/src/app/nav-bar/pages/nav-bar/nav-bar.component.ts
  lib/javax.ejb.jar
  lib/javax.jms.jar
  lib/javax.persistence.jar
  lib/javax.resource.jar
  lib/javax.servlet.jsp.jar
  lib/javax.servlet.jsp.jstl.jar
  lib/javax.transaction.jar
Labels: type:features

#75 KIEV21DEVS-26 front deploy
  .github/workflows/dockerhub.yml
  frontend/.dockerignore
  frontend/Dockerfile
Labels: type:features

#79 KIEV21DEVS-230 Validation added, checkout started.
  backend/src/main/java/com/eshop/backend/checkout/CheckoutController.java
  backend/src/main/java/com/eshop/backend/search/SearchController.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/_service/rest.service.ts
  frontend/src/app/account/profile/profile.component.html
  frontend/src/app/account/profile/profile.component.ts
  frontend/src/app/account/search/search.component.css
  frontend/src/app/account/search/search.component.html
  frontend/src/app/account/search/search.component.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/checkout/checkout.component.css
  frontend/src/app/checkout/checkout.component.html
  frontend/src/app/checkout/checkout.component.spec.ts
  frontend/src/app/checkout/checkout.component.ts
Labels: type:fix

#82 KIEV21DEVS-131 Feature/products code fix
  backend/src/main/java/com/eshop/backend/catalog/ProductCRUDController.java
  backend/src/main/java/com/eshop/backend/catalog/service/ProductService.java
  backend/src/main/java/com/eshop/backend/catalog/service/ProductServiceImp.java
  backend/src/main/java/com/eshop/backend/product/dao/ProductDao.java
  backend/src/main/java/com/eshop/backend/product/dao/ProductDaoImpl.java
  frontend/src/app/_service/product/product.service.ts
  frontend/src/app/products/product-list/product-list.component.html
  frontend/src/app/products/product-list/product-list.component.ts
  frontend/src/app/products/product-search/product-search.component.ts
  frontend/src/app/products/product/product.component.html
  frontend/src/app/work-space/manager-workspace/manager-workspace.component.ts
Labels: type:features, type:fix

#83 KIEV21DEVS-236
  backend/src/main/java/com/eshop/backend/admin/AdminController.java
  backend/src/main/java/com/eshop/backend/admin/adminDto.java
  backend/src/main/java/com/eshop/backend/admin/services/AdminService.java
  backend/src/main/java/com/eshop/backend/admin/services/AdminServiceImp.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDao.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDaoImpl.java
  backend/src/main/java/com/eshop/backend/courier/CourierController.java
  backend/src/main/java/com/eshop/backend/courier/dto/courierDto.java
  backend/src/main/java/com/eshop/backend/courier/service/CourierService.java
  backend/src/main/java/com/eshop/backend/courier/service/CourierServiceImp.java
  backend/src/main/java/com/eshop/backend/utils/Employee/EmployeeService.java
  backend/src/main/resources/db/migration/init/V2__create_tables.sql
  frontend/src/app/_model/admin.ts
  frontend/src/app/_model/coucab.ts
  frontend/src/app/_model/courierDto.ts
  frontend/src/app/_service/rest.service.ts
  frontend/src/app/_service/search/adminService.ts
  frontend/src/app/account/cartdeliv/cartdeliv.component.css
  frontend/src/app/account/cartdeliv/cartdeliv.component.html
  frontend/src/app/account/cartdeliv/cartdeliv.component.spec.ts
  frontend/src/app/account/cartdeliv/cartdeliv.component.ts
  frontend/src/app/account/courier-cabinet/coucab.component.html
  frontend/src/app/account/courier-cabinet/coucab.component.ts
  frontend/src/app/account/search/search.component.html
  frontend/src/app/account/search/search.component.ts
  frontend/src/app/app.module.ts
Labels: type:fix

#89 KIEV21DEVS-134 popular products
  backend/src/main/java/com/eshop/backend/product/dao/ProductDaoImpl.java
  backend/src/main/resources/db/migration/init/V2__create_tables.sql
  frontend/src/app/main-page/main-page.component.html
  frontend/src/app/products/product-card/product-card.component.html
  frontend/src/app/products/product/product.component.html
Labels: type:features, type:fix

#90 Feature/compare products
  frontend/src/app/_model/productToCompare.ts
  frontend/src/app/_service/compare/compare.service.spec.ts
  frontend/src/app/_service/compare/compare.service.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/nav-bar/pages/nav-bar/nav-bar.component.html
  frontend/src/app/products/compare/compare.component.css
  frontend/src/app/products/compare/compare.component.html
  frontend/src/app/products/compare/compare.component.spec.ts
  frontend/src/app/products/compare/compare.component.ts
  frontend/src/app/products/product-list/product-list.component.html
  frontend/src/app/products/product/product.component.html
  frontend/src/app/products/product/product.component.ts
  frontend/src/app/products/products.module.ts
Labels: type:features

#88 KIEV21DEVS-124 Feature/account
  frontend/src/app/account/search/search.component.html
  frontend/src/app/account/search/search.component.ts
  frontend/src/app/checkout/checkout.component.html
  frontend/src/app/checkout/checkout.component.ts
  frontend/src/app/shopping-cart/cart/shopping-cart.component.html
  frontend/src/app/shopping-cart/cart/shopping-cart.component.ts
Labels: type:fix

#92 KIEV21DEVS-216 fix/shop cart
  backend/src/main/java/com/eshop/backend/auth/LoginController.java
  backend/src/main/java/com/eshop/backend/auth/RegistrationController.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDaoImpl.java
  backend/src/main/java/com/eshop/backend/auth/utils/Role.java
  backend/src/main/java/com/eshop/backend/product/dao/ProductDao.java
  backend/src/main/java/com/eshop/backend/product/dao/ProductDaoImpl.java
  backend/src/main/java/com/eshop/backend/shoping_card/ShoppingCartController.java
  backend/src/main/java/com/eshop/backend/shoping_card/ShoppingCartDao.java
  backend/src/main/java/com/eshop/backend/shoping_card/ShoppingCartDaoImpl.java
  backend/src/main/java/com/eshop/backend/shoping_card/ShoppingCartService.java
  backend/src/main/java/com/eshop/backend/shoping_card/ShoppingCartServiceImpl.java
  backend/src/main/java/com/eshop/backend/user/settings/services/SettingsServiceImpl.java
  backend/src/main/resources/db/migration/init/V1__create_tables.sql
  backend/src/main/resources/db/migration/init/V2__create_tables.sql
  frontend/src/app/_model/status.ts
  frontend/src/app/_service/auth/auth.service.ts
  frontend/src/app/_service/shopping-cart/shopping-cart.service.ts
  frontend/src/app/account/profile/profile.component.ts
  frontend/src/app/authorization/reset-password/reset-password.component.ts
  frontend/src/app/main-page/main-page.component.ts
  frontend/src/app/nav-bar/pages/nav-bar/nav-bar.component.html
  frontend/src/app/products/product-card/product-card.component.ts
  frontend/src/app/shopping-cart/cart/shopping-cart.component.html
  frontend/src/app/shopping-cart/cart/shopping-cart.component.ts
  frontend/src/app/shopping-cart/product-in-cart/product-in-cart.component.ts
Labels: type:fix

#93 Fix products code
  backend/src/main/java/com/eshop/backend/product/dao/ProductDaoImpl.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/products/product-create/product-create.component.ts
  frontend/src/app/products/product-edit/product-edit.component.ts
  frontend/src/app/products/product-manager/product-manager.component.ts
  frontend/src/app/products/product/product.component.ts
Labels: type:fix

#94 KIEV21DEVS-230 feature/checkout
  backend/src/main/java/com/eshop/backend/auth/config/WebSecurity.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDao.java
  backend/src/main/java/com/eshop/backend/auth/dao/user/AuthorizedUserDaoImpl.java
  backend/src/main/java/com/eshop/backend/checkout/CheckoutController.java
  backend/src/main/java/com/eshop/backend/checkout/CheckoutDao.java
  backend/src/main/java/com/eshop/backend/checkout/CheckoutDaoImpl.java
  backend/src/main/java/com/eshop/backend/checkout/CheckoutService.java
  backend/src/main/java/com/eshop/backend/checkout/CheckoutServiceImpl.java
  backend/src/main/java/com/eshop/backend/checkout/OrderCheckoutDto.java
  backend/src/main/java/com/eshop/backend/shoping_card/ShoppingCartDaoImpl.java
  backend/src/main/java/com/eshop/backend/user/settings/services/SettingsServiceImpl.java
  frontend/src/app/_service/checkout/checkout.service.spec.ts
  frontend/src/app/_service/checkout/checkout.service.ts
  frontend/src/app/_service/shopping-cart/shopping-cart.service.ts
  frontend/src/app/app.module.ts
  frontend/src/app/checkout/checkout.component.html
  frontend/src/app/checkout/checkout.component.ts
  frontend/src/app/products/product-edit/product-edit.component.ts
  frontend/src/app/shopping-cart/cart/shopping-cart.component.html
  frontend/src/app/shopping-cart/cart/shopping-cart.component.ts
  frontend/src/app/shopping-cart/product-in-cart/product-in-cart.component.html
  frontend/src/app/shopping-cart/product-in-cart/product-in-cart.component.ts
Labels: type:features

#95 links to workspaces
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/nav-bar/components/workspace-link/workspace-link.component.css
  frontend/src/app/nav-bar/components/workspace-link/workspace-link.component.html
  frontend/src/app/nav-bar/components/workspace-link/workspace-link.component.spec.ts
  frontend/src/app/nav-bar/components/workspace-link/workspace-link.component.ts
  frontend/src/app/nav-bar/nav-bar.module.ts
  frontend/src/app/nav-bar/pages/nav-bar/nav-bar.component.html
  frontend/src/app/products/product-list/product-list.component.ts
  frontend/src/app/products/product/product.component.html
  frontend/src/app/products/products.module.ts
  frontend/src/app/workplace/workplace.component.css
  frontend/src/app/workplace/workplace.component.html
  frontend/src/app/workplace/workplace.component.spec.ts
  frontend/src/app/workplace/workplace.component.ts
Labels: type:features

#100 KIEV21DEVS-343 Footer and carousel
  frontend/src/app/app.component.css
  frontend/src/app/app.component.html
  frontend/src/app/main-page/main-page.component.css
  frontend/src/app/main-page/main-page.component.html
  frontend/src/app/products/product-list/product-list.component.css
  frontend/src/app/products/product-list/product-list.component.html
  frontend/src/app/products/product/product.component.css
  frontend/src/app/products/product/product.component.html
  frontend/src/app/workplace/workplace.component.css
  frontend/src/app/workplace/workplace.component.html
  frontend/src/assets/img/main-carousel-item-1.jpg
  frontend/src/assets/img/main-carousel-item-1.png
  frontend/src/assets/img/main-carousel-item-2.jpg
  frontend/src/assets/img/main-carousel-item-2.png
  frontend/src/assets/img/main-carousel-item-3.png
Labels: type:features

#105 Fix/courier
  backend/src/main/java/com/eshop/backend/Socket/Greeting.java
  backend/src/main/java/com/eshop/backend/Socket/GreetingController.java
  backend/src/main/java/com/eshop/backend/Socket/HelloMessage.java
  backend/src/main/java/com/eshop/backend/Socket/Message.java
  backend/src/main/java/com/eshop/backend/Socket/NotificationDispatcher.java
  backend/src/main/java/com/eshop/backend/Socket/NotificationsController.java
  backend/src/main/java/com/eshop/backend/Socket/WebSocketConfig.java
  backend/src/main/java/com/eshop/backend/auth/config/WebSecurity.java
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/socket/notifications/WebSocketAPI.ts
  frontend/src/app/socket/notifications/notification.component.html
  frontend/src/app/socket/notifications/notification.component.ts
  frontend/src/index.html
Labels: type:fix

#107 Lastbranch
  backend/src/main/java/com/eshop/backend/checkout/CheckoutServiceImpl.java
  backend/src/main/java/com/eshop/backend/controller/SearchController.java
  backend/src/main/java/com/eshop/backend/courier/CourierController.java
  backend/src/main/java/com/eshop/backend/courier/dto/calendar.java
  backend/src/main/java/com/eshop/backend/courier/service/CourierService.java
  backend/src/main/java/com/eshop/backend/courier/service/CourierServiceImp.java
  backend/src/main/java/com/eshop/backend/repository/implementations/AuthorizedUserDaoImpl.java
  backend/src/main/java/com/eshop/backend/repository/interfaces/AuthorizedUserDao.java
  backend/src/main/java/com/eshop/backend/service/implementations/EmployeeService.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/_model/calendar.ts
  frontend/src/app/_service/rest.service.ts
  frontend/src/app/account/courier-cabinet/coucab.component.html
  frontend/src/app/account/courier-cabinet/coucab.component.ts
Labels: type:fix
